import {mock} from 'bun:test';import assert from 'node:assert/strict';
const applied=[],confirmed=[],messages=[];mock.module('../src/community-records.ts',()=>({applyChange:async(c,d)=>applied.push({c,d}),confirmChange:async(...args)=>confirmed.push(args)}));mock.module('../src/community-runtime.ts',()=>({ephemeral:async(c,m)=>messages.push(m)}));const {handleReflectionReport}=await import('../src/community-reflection.ts');const originalNow=Date.now;Date.now=()=>Date.parse('2026-09-14T03:00:00Z');const scope={teamId:'TQA',channelId:'CQA',userId:'UQA'},day={...scope,date:'2026-09-14',goal:'논문 공유',outcome:'pending',reflection:'',resting:false,revision:7};const context={scope,source:'1.000001',thread:'0.000001',date:day.date,store:{async history(){return[day,{...day,date:'2026-09-13'}];}}};const text='후기:\n9/14: 완료. 교수님께 예약 메세지를 걸어두었는데 어떤 피드백이 올지...';
try{assert.equal(await handleReflectionReport(context,text),true);assert.equal(applied.length,1);assert.equal(confirmed.length,0);assert.equal(applied[0].d.date,'2026-09-14');assert.equal(applied[0].d.action,'reflection');assert.equal(applied[0].d.outcome,'complete');assert.equal(applied[0].d.text,text);assert.equal(applied[0].d.expectedRevision,7);assert.equal(applied[0].d.userId,'UQA');
await handleReflectionReport(context,text.replace('9/14','9/13'));assert.equal(confirmed.length,1);assert.equal(confirmed[0][0].date,'2026-09-13');assert.equal(applied.length,1);
for(const patch of [{reflection:'existing'},{resting:true},{outcome:'not_done'}]){await handleReflectionReport({...context,store:{async history(){return[{...day,...patch}];}}},text);}assert.equal(applied.length,1);assert.equal(confirmed.length,4);
await handleReflectionReport({...context,store:{async history(){return[];}}},text);assert.match(messages.at(-1).text,/등록된 원씽이 없/);assert.equal(applied.length,1);
await handleReflectionReport(context,text.replace('9/14','9/31'));assert.equal(applied.length,1);
console.log('PASS actual multiline first review auto-saves scoped date+verbatim body; past/overwrite/rest/conflict confirm; missing/invalid no writes');}finally{Date.now=originalNow;}
Date.now=()=>Date.parse('2026-09-14T03:00:00Z');
try{const n=applied.length;for(const input of ['후기:\n9/14: 완료 예정입니다.','후기: 완료했나요?','후기: 완료하지 못했어요.']){assert.equal(await handleReflectionReport(context,input),true);}assert.equal(applied.length,n);console.log('PASS unclear explicit reflection headers cannot fall through to automatic AI writes');}finally{Date.now=originalNow;}
