import {mock} from 'bun:test';import assert from 'node:assert/strict';
const applied=[],confirmed=[],messages=[];mock.module('../src/community-records.ts',()=>({applyChange:async(c,d)=>applied.push({c,d}),confirmChange:async(...args)=>confirmed.push(args)}));mock.module('../src/community-runtime.ts',()=>({ephemeral:async(c,m)=>messages.push(m)}));const {handleReflectionReport}=await import('../src/community-reflection.ts');const originalNow=Date.now;Date.now=()=>Date.parse('2026-09-14T03:00:00Z');const scope={teamId:'TQA',channelId:'CQA',userId:'UQA'},day={...scope,date:'2026-09-14',goal:'논문 공유',outcome:'pending',reflection:'',resting:false,revision:7};const context={key:'incoming:1.000001',scope,source:'1.000001',thread:'0.000001',date:day.date,store:{async history(){return[day,{...day,date:'2026-09-13'}];}}};const text='후기:\n9/14: 완료. 교수님께 예약 메세지를 걸어두었는데 어떤 피드백이 올지...';
try{assert.equal(await handleReflectionReport(context,text),true);assert.equal(applied.length,1);assert.equal(confirmed.length,0);assert.equal(applied[0].d.date,'2026-09-14');assert.equal(applied[0].d.action,'reflection');assert.equal(applied[0].d.outcome,'complete');assert.equal(applied[0].d.text,text);assert.equal(applied[0].d.expectedRevision,7);assert.equal(applied[0].d.userId,'UQA');
await handleReflectionReport(context,text.replace('9/14','9/13'));assert.equal(confirmed.length,1);assert.equal(confirmed[0][0].date,'2026-09-13');assert.equal(applied.length,1);
for(const patch of [{reflection:'existing'},{resting:true},{outcome:'not_done'}]){await handleReflectionReport({...context,store:{async history(){return[{...day,...patch}];}}},text);}assert.equal(applied.length,1);assert.equal(confirmed.length,4);
await handleReflectionReport({...context,store:{async history(){return[];}}},text);assert.match(messages.at(-1).text,/등록된 ONE THING이 없/);assert.equal(applied.length,1);
await handleReflectionReport(context,text.replace('9/14','9/31'));assert.equal(applied.length,1);
console.log('PASS actual multiline first review auto-saves scoped date+verbatim body; past/overwrite/rest/conflict confirm; missing/invalid no writes');}finally{Date.now=originalNow;}
Date.now=()=>Date.parse('2026-09-14T03:00:00Z');
try{const n=applied.length;for(const input of ['후기:\n9/14: 완료 예정입니다.','후기: 완료했나요?','후기: 완료하지 못했어요.']){assert.equal(await handleReflectionReport(context,input),true);}assert.equal(applied.length,n);console.log('PASS unclear explicit reflection headers cannot fall through to automatic AI writes');}finally{Date.now=originalNow;}

Date.now=()=>Date.parse('2026-09-14T03:00:00Z');
try{const before=applied.length;await handleReflectionReport(context,'후기: 완료.');assert.equal(applied.length,before+1);assert.equal(applied.at(-1).d.action,'complete');assert.equal(applied.at(-1).d.text,undefined);for(const text of ['후기: 완료. 하지만 아직 절반밖에 못 했어요.','후기: 완료. 사실은 아직 다 못했어요.','후기: 완료. 이건 예시이고 제 목표는 미완료입니다.','후기: 완료. 라고 쓰면 완료 처리되나요?']){await handleReflectionReport(context,text);}assert.equal(applied.length,before+1);console.log('PASS status-only completion is not a review; contradictory/meta text causes zero automatic writes');}finally{Date.now=originalNow;}

Date.now=()=>Date.parse('2026-09-14T03:00:00Z');
try{const a=applied.length,c=confirmed.length;await handleReflectionReport(context,'후기: 9/13: 완료.');assert.equal(confirmed.at(-1)[3],'complete');assert.equal(confirmed.at(-1)[0].date,'2026-09-13');const c2=confirmed.length;await handleReflectionReport(context,'후기: 9/13: 완료. 하지만 절반만 했어요.');assert.equal(confirmed.length,c2);assert.equal(applied.length,a);console.log('PASS past status-only confirmation cannot overwrite review; ambiguous dated body never proposes wrong-date mutation');}finally{Date.now=originalNow;}
Date.now=()=>Date.parse('2026-09-14T03:00:00Z');try{const a=applied.length,c=confirmed.length;for(const input of ['후기:\n9 / 13: 완료. 배웠어요','후기:\n9-13: 완료. 배웠어요'])await handleReflectionReport(context,input);assert.equal(confirmed.length,c);assert.equal(applied.length,a);for(const input of ['후기: 완료. 실제로는 실패했어요.','후기: 완료. 라는 문장은 예문입니다.','후기: 완료. 라는 말은 거짓말이에요.'])await handleReflectionReport(context,input);assert.equal(applied.length,a);console.log('PASS spaced/unsupported dates cannot produce wrong-date confirmation; extra negative/meta cases cannot auto-complete');}finally{Date.now=originalNow;}
Date.now=()=>Date.parse('2026-09-14T03:00:00Z');try{const a=applied.length,c=confirmed.length;assert.equal(await handleReflectionReport(context,'후기:\n9/14: 부분 완료. QA 편집 이벤트에서는 절반 진행으로 정정합니다.'),true);assert.equal(applied.length,a);assert.equal(confirmed.length,c);console.log('PASS narrative correction wording cannot bypass safe explicit-header date handling');}finally{Date.now=originalNow;}
